In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from data_helper import DataHelper
from grid_search import MyGridSearch

In [17]:
columns = ['pool','day_of_week','month','minute_of_day','year']
# Add weather
parameteres = {	'n_estimators': [20] ,
                'max_depth': [20, 50] ,
                'min_samples_split': [2, 5],
                'min_samples_leaf': [1, 2]}

mgs = MyGridSearch('ExtraTreesClassifier',parameteres)
mgs.fit(columns)

1 out of 8 done for parameters ExtraTreesClassifier(random_state=17, n_estimators=20, max_depth=20, min_samples_split=2, min_samples_leaf=1) with score 1563.6, best MSE so far = 1563.6
2 out of 8 done for parameters ExtraTreesClassifier(random_state=17, n_estimators=20, max_depth=20, min_samples_split=2, min_samples_leaf=2) with score 2849.7, best MSE so far = 1563.6
3 out of 8 done for parameters ExtraTreesClassifier(random_state=17, n_estimators=20, max_depth=20, min_samples_split=5, min_samples_leaf=1) with score 1553.3, best MSE so far = 1553.3
4 out of 8 done for parameters ExtraTreesClassifier(random_state=17, n_estimators=20, max_depth=20, min_samples_split=5, min_samples_leaf=2) with score 4545.4, best MSE so far = 1553.3
5 out of 8 done for parameters ExtraTreesClassifier(random_state=17, n_estimators=20, max_depth=50, min_samples_split=2, min_samples_leaf=1) with score 1440.9, best MSE so far = 1440.9
6 out of 8 done for parameters ExtraTreesClassifier(random_state=17, n_esti

In [ ]:
parameteres = {	'n_estimators': [20, 50, 100],
                'learning_rate': [0.01,0.1,0.5]}

mgs = MyGridSearch('AdaBoostClassifier',parameteres)
mgs.fit(columns)

In [ ]:
parameteres = {	'C': [0.001, 0.01, 0.1, 1, 10],
                'gamma': [0.001, 0.01, 0.1, 1]}
parameteres = {	'C': [0.001, 0.01, 0.1, 1, 10]}
mgs = MyGridSearch('SVC',parameteres)
mgs.fit(['pool','day_of_week','month','hour','minute'] )

In [11]:
from hmmlearn.hmm import MultinomialHMM, GaussianHMM
import numpy as np

In [3]:
dh = DataHelper()
columns = ['pool','lines_reserved','day_of_week']
x_train, y_train, x_test, y_test = dh.generate_feature_vectors(columns, 1)
print(x_train)

[[ 0.  0.  3.]
 [ 0.  0.  3.]
 [ 0.  0.  3.]
 ...
 [27.  0.  3.]
 [21.  0.  3.]
 [14.  0.  3.]]


In [12]:
x, x_len = dh.generate_feature_vectors_for_hmm(columns)
g = GaussianHMM(n_components=400)

In [13]:
g.fit(x, x_len)

GaussianHMM(algorithm='viterbi', covariance_type='diag', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=400, n_iter=10, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [14]:
import pickle
with open("gmm.pkl", "wb") as file: pickle.dump(g, file)